### ISSUE TITLE
Won't compile using build.py

### ISSUE THREAD

**Issue by PyroLagus** [tguillem/mpd#1]
This is the output after running build.py for the second time (for cleaner output).

```
codehero@wheatley ~/Software/mpd/android (git)-[android-2] % ./build.py /opt/android-sdk/ /opt/android-ndk/
configure.ac:39: installing './compile'
libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/bin/sh: /home/codehero/Software/mpd/android/lib/src/libid3tag-0.15.1b/missing: No such file or directory
configure: WARNING: 'missing' script is too old or missing
checking for arm-linux-androideabi-strip... /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... arm-unknown-linux-androideabi
checking for arm-linux-androideabi-gcc... /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc accepts -g... yes
checking for /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc option to accept ISO C89... none needed
checking whether /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc... none
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc... /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/arm-linux-androideabi/bin/ld
checking if the linker (/opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/arm-linux-androideabi/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... no
checking for arm-linux-androideabi-dumpbin... no
checking for arm-linux-androideabi-link... no
checking for dumpbin... no
checking for link... link -dump
configure: WARNING: using cross tools not prefixed with host triplet
checking the name lister (nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to arm-unknown-linux-androideabi format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/arm-linux-androideabi/bin/ld option to reload object files... -r
checking for arm-linux-androideabi-objdump... no
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for arm-linux-androideabi-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for arm-linux-androideabi-ar... /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar
checking for archiver @FILE support... @
checking for arm-linux-androideabi-strip... (cached) /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip
checking for arm-linux-androideabi-ranlib... no
checking for ranlib... ranlib
checking command to parse nm output from /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc object... ok
checking for sysroot... /opt/android-ndk/platforms/android-14/arch-arm
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for arm-linux-androideabi-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc supports -fno-rtti -fno-exceptions... no
checking for /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc option to produce PIC... -fPIC -DPIC
checking if /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc PIC flag -fPIC -DPIC works... yes
checking if /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc static flag -static works... yes
checking if /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc supports -c -o file.o... yes
checking if /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc supports -c -o file.o... (cached) yes
checking whether the /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc linker (/opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/arm-linux-androideabi/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... Android linker
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking for ANSI C header files... (cached) yes
checking assert.h usability... yes
checking assert.h presence... yes
checking for assert.h... yes
checking for unistd.h... (cached) yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for ftruncate... yes
checking for compress2 in -lz... yes
checking whether to enable profiling... no
checking whether to enable debugging... default
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating msvc++/Makefile
config.status: creating libid3tag.list
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: creating config.h
  CC       version.lo
  CC       ucs4.lo
  CC       latin1.lo
  CC       utf16.lo
  CC       field.lo
  CC       genre.lo
/bin/sh: /home/codehero/Software/mpd/android/lib/src/libid3tag-0.15.1b/depcomp: No such file or directory
Makefile:558: recipe for target 'latin1.lo' failed
make[2]: *** [latin1.lo] Error 127
make[2]: *** Waiting for unfinished jobs....
  CC       utf8.lo
  CC       compat.lo
  CC       render.lo
  CC       frametype.lo
/bin/sh: /home/codehero/Software/mpd/android/lib/src/libid3tag-0.15.1b/depcomp: No such file or directory
Makefile:558: recipe for target 'utf16.lo' failed
make[2]: *** [utf16.lo] Error 127
/bin/sh: /home/codehero/Software/mpd/android/lib/src/libid3tag-0.15.1b/depcomp: No such file or directory
  CC       frame.lo
  CC       parse.lo
Makefile:558: recipe for target 'version.lo' failed
make[2]: *** [version.lo] Error 127
/bin/sh: /home/codehero/Software/mpd/android/lib/src/libid3tag-0.15.1b/depcomp: No such file or directory
Makefile:558: recipe for target 'field.lo' failed
make[2]: *** [field.lo] Error 127
/bin/sh: /home/codehero/Software/mpd/android/lib/src/libid3tag-0.15.1b/depcomp: No such file or directory
/bin/sh: /home/codehero/Software/mpd/android/lib/src/libid3tag-0.15.1b/depcomp: No such file or directory
Makefile:558: recipe for target 'frame.lo' failed
make[2]: *** [frame.lo] Error 127
Makefile:558: recipe for target 'parse.lo' failed
make[2]: *** [parse.lo] Error 127
/bin/sh: /home/codehero/Software/mpd/android/lib/src/libid3tag-0.15.1b/depcomp: No such file or directory
Makefile:558: recipe for target 'compat.lo' failed
make[2]: *** [compat.lo] Error 127
/bin/sh: /home/codehero/Software/mpd/android/lib/src/libid3tag-0.15.1b/depcomp: No such file or directory
/bin/sh: /home/codehero/Software/mpd/android/lib/src/libid3tag-0.15.1b/depcomp: No such file or directory
Makefile:558: recipe for target 'render.lo' failed
make[2]: *** [render.lo] Error 127
Makefile:558: recipe for target 'frametype.lo' failed
make[2]: *** [frametype.lo] Error 127
/bin/sh: /home/codehero/Software/mpd/android/lib/src/libid3tag-0.15.1b/depcomp: No such file or directory
/bin/sh: /home/codehero/Software/mpd/android/lib/src/libid3tag-0.15.1b/depcomp: No such file or directory
Makefile:558: recipe for target 'utf8.lo' failed
make[2]: *** [utf8.lo] Error 127
Makefile:558: recipe for target 'genre.lo' failed
make[2]: *** [genre.lo] Error 127
/bin/sh: /home/codehero/Software/mpd/android/lib/src/libid3tag-0.15.1b/depcomp: No such file or directory
Makefile:558: recipe for target 'ucs4.lo' failed
make[2]: *** [ucs4.lo] Error 127
Makefile:599: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
Makefile:424: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "./build.py", line 419, in <module>
    x.build()
  File "./build.py", line 249, in build
    subprocess.check_call(['/usr/bin/make', '--quiet', '-j12'], cwd=build)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/make', '--quiet', '-j12']' returned non-zero exit status 2
./build.py /opt/android-sdk/ /opt/android-ndk/  4.80s user 0.67s system 73% cpu 7.471 total
```

**Comment by gdub010101** [comment]
To workaround "depcomp: No such file or directory" you can edit build.py and add --disable-dependency-tracking to the options for libid3tag and libmad

AutotoolsProject(
        'ftp://ftp.mars.org/pub/mpeg/libid3tag-0.15.1b.tar.gz',
        'e5808ad997ba32c498803822078748c3',
        'lib/libid3tag.a',
        ['--disable-shared', '--enable-static', '--disable-dependency-tracking'],
        autogen=True,
    ),

```
AutotoolsProject(
    'ftp://ftp.mars.org/pub/mpeg/libmad-0.15.1b.tar.gz',
    '1be543bc30c56fb6bea1d7bf6a64e66c',
    'lib/libmad.a',
    ['--disable-shared', '--enable-static', '--disable-dependency-tracking'],
    autogen=True,
),
```

However, even after the build.py workaround above and editing the Makefile manually to change android-17 to another target, eventually I get this

/home/grant/mpd-android-nfs2/src/fs/StandardDirectory.cxx:71:3: error: use of undeclared identifier 'getpwnam_r'
                getpwnam_r(name, &pw, buf.data(), buf.size(), &result);
                ^
/home/grant/mpd-android-nfs2/src/fs/StandardDirectory.cxx:80:3: error: use of undeclared identifier 'getpwuid_r'
                getpwuid_r(uid, &pw, buf.data(), buf.size(), &result);
                ^
2 errors generated.
Makefile:8567: recipe for target 'src/fs/libfs_a-StandardDirectory.o' failed

It would be great to have some way to build this.
